// Generated by CoffeeScript 1.10.0
(function() {
  var addSummaryToStatsTable, createStatsTable, gameBreakout, historyTable, init, lastXSummary, statsBaseTable;

  statsBaseTable = "<table class='statsTable' id='matchHistoryStats' style='width:100%;table-layout:auto;empty-cells:show;'> <tr> <th>Last X Games</th> <th>Wins</th> <th>Losses</th> <th>Win %</th> <th>Net MMR</th> </tr> <tbody id='statsTableBody'> </tbody> </table> ";

  gameBreakout = [10, 20, 50, 100];

  historyTable = null;

  init = function() {
    return this.historyTable = $('#ctl00_MainContent_ctl00_MainContent_RadGridMatchHistoryPanel');
  };

  lastXSummary = function(rows) {
    var i, len, losses, mmrChange, netMMR, row, winrate, wins;
    wins = 0;
    losses = 0;
    netMMR = 0;
    for (i = 0, len = rows.length; i < len; i++) {
      row = rows[i];
      if ($(row).css('background-color') === 'rgb(144, 238, 144)') {
        wins += 1;
      } else {
        losses += 1;
      }
      mmrChange = parseInt($(row).find("td").eq(8).html(), 10);
      if (!isNaN(mmrChange)) {
        netMMR += mmrChange;
      }
    }
    winrate = (wins / rows.length) * 100;
    return {
      games: rows.length,
      wins: wins,
      losses: losses,
      winrate: winrate,
      netMMR: netMMR
    };
  };

  createStatsTable = function() {
    var i, len, rows, statsTable, summary, x, xrows;
    this.historyTable.before(statsBaseTable);
    rows = this.historyTable.find("tr.rgRow");
    statsTable = $('#matchHistoryStats');
    for (i = 0, len = gameBreakout.length; i < len; i++) {
      x = gameBreakout[i];
      xrows = rows.slice(0, +(x - 1) + 1 || 9e9);
      summary = lastXSummary(xrows);
      addSummaryToStatsTable(summary);
    }
  };

  addSummaryToStatsTable = function(summary) {
    var statRow;
    statRow = "<tr> <td>" + summary.games + "</td> <td>" + summary.wins + "</td> <td>" + summary.losses + "</td> <td>" + summary.winrate + "</td> <td>" + summary.netMMR + "</td> </tr> ";
    return $("#statsTableBody").append(statRow);
  };

  init();

  createStatsTable();

}).call(this);
